# Check `docs/pipeline.md` to get info about this file
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

  - name: kite
    type: docker-image
    source:
      repository: heliostech/kite
      tag: v0.2.0

resources:
  - name: k8s
    type: kite
    source:
      json_key: ((gcr_password))
      kubeconfig: ((kubeconfig))

  - name: peatio-charts-repository
    type: git
    source:
      uri: git@github.com:rubykube/peatio-charts.git
      branch: master
      private_key: ((git_private_key))

  - name: pull-requests
    type: pull-request
    source:
      access_token: ((github_token))
      base: master
      private_key: ((git_private_key))
      repo: rubykube/peatio-charts
      uri: git@github.com:rubykube/peatio-charts.git

  - name: peatio-charts-image
    type: docker-image
    source:
      repository: gcr.io/hc-public/peatio/charts
      username: _json_key
      password: ((gcr_password))

jobs:
  - name: pr-build
    plan:
      - get: pull-requests
        trigger: true
      - task: tag
        file: pull-requests/config/pipelines/tasks/create-pull-requests-tag.yml
      - put: peatio-charts-image
        params:
          build: pull-requests
          tag: tag/name

  - name: pr-unit
    serial: true
    plan:
      - get: pull-requests
        passed: [pr-build]
        trigger: true
      - get: peatio-charts-image
        passed: [pr-build]
        trigger: true
      - put: pull-requests
        params:
          path: pull-requests
          status: pending
      - task: run-tests
        image: peatio-charts-image
        file: pull-requests/config/pipelines/tasks/run-unit.yml
        on_success:
          do:
          - put: pull-requests
            params:
              path: pull-requests
              status: success
        on_failure:
          do:
          - put: pull-requests
            params:
              path: pull-requests
              status: failure

  - name: master-build
    serial: true
    plan:
      - get: peatio-charts-repository
        trigger: true
      - task: tag
        file: peatio-charts-repository/config/pipelines/tasks/create-repository-tag.yml
      - put: peatio-charts-image
        params:
          build: peatio-charts-repository
          tag: tag/name

  - name: master-unit
    serial: true
    plan:
      - get: peatio-charts-repository
        passed: [master-build]
        trigger: true
      - get: peatio-charts-image
        passed: [master-build]
        trigger: true
      - task: run-tests
        image: peatio-charts-image
        file: peatio-charts-repository/config/pipelines/tasks/run-unit.yml

  - name: master-deploy
    serial: true
    plan:
      - get: peatio-charts-repository
        passed: [master-unit]
        trigger: true
      - put: k8s
        params:
          command: "bash -xc 'cd /tmp/build/put/peatio-charts-repository && VERSION=$(git rev-parse --short=8 HEAD) make deploy'"
